# Generated by Django 4.2.22 on 2025-11-09 22:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contentstore', '0001_add_organization_admin_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='chalixorganization',
            name='admin',
            field=models.ForeignKey(blank=True, help_text='Admin user responsible for this organization', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='administered_organizations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
    ]
