# Generated by Django 4.2.22 on 2025-09-12 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contentstore', '0041_create_default_course_types'),
        ('contentstore', '0044_create_program_models'),
    ]

    operations = [
    ]
