# Generated by Django 4.2.22 on 2025-09-14 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contentstore', '0045_merge_20250912_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='localcourse',
            name='course_type',
            field=models.CharField(blank=True, help_text='Type of course (bat-buoc, tuy-chon, co-quan)', max_length=50),
        ),
        migrations.AddField(
            model_name='localcourse',
            name='template_program',
            field=models.ForeignKey(blank=True, help_text='Program template used to create this course', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='template_courses', to='contentstore.localprogram'),
        ),
    ]
