# Generated by Django 4.2.22 on 2025-09-16 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contentstore', '0047_add_course_key_to_localcourse'),
        ('contentstore', '0047_add_short_description_to_localprogram'),
    ]

    operations = [
    ]
