# Generated by Django 4.2.22 on 2025-09-21 03:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contentstore', '0048_merge_20250916_2130'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlideConversionJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=255)),
                ('slide_id', models.CharField(max_length=255)),
                ('file_name', models.CharField(max_length=1024)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('pdf_file_name', models.CharField(blank=True, max_length=1024, null=True)),
                ('pdf_url', models.TextField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
