# Generated by Django 4.2.22 on 2025-09-22 22:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import opaque_keys.edx.django.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contentstore', '0049_slideconversionjob'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitMediaFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Media File ID')),
                ('unit_id', models.CharField(db_index=True, help_text='The unique identifier of the course unit this media belongs to', max_length=255, verbose_name='Unit ID')),
                ('course_id', opaque_keys.edx.django.models.CourseKeyField(db_index=True, help_text='The course key this media belongs to', max_length=255, verbose_name='Course ID')),
                ('media_type', models.CharField(choices=[('video', 'Video'), ('slide', 'Slide')], db_index=True, help_text='Type of media file (video or slide)', max_length=10, verbose_name='Media Type')),
                ('file_name', models.CharField(help_text='Original filename as uploaded by user', max_length=255, verbose_name='File Name')),
                ('display_name', models.CharField(blank=True, help_text='User-friendly name for the media file', max_length=255, verbose_name='Display Name')),
                ('file_size', models.BigIntegerField(help_text='Size of the file in bytes', verbose_name='File Size')),
                ('file_type', models.CharField(help_text='MIME type of the file (e.g., video/mp4, application/pdf)', max_length=100, verbose_name='File Type')),
                ('file_path', models.CharField(help_text='Relative path to the stored file', max_length=500, verbose_name='File Path')),
                ('upload_url', models.URLField(help_text='Public URL for accessing the uploaded file', verbose_name='Upload URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('uploaded_by', models.ForeignKey(blank=True, help_text='User who uploaded this media file', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_unit_media', to=settings.AUTH_USER_MODEL, verbose_name='Uploaded By')),
            ],
            options={
                'verbose_name': 'Unit Media File',
                'verbose_name_plural': 'Unit Media Files',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='SlideConversionJob',
        ),
        migrations.AddIndex(
            model_name='unitmediafile',
            index=models.Index(fields=['unit_id', 'media_type'], name='contentstor_unit_id_a0f54e_idx'),
        ),
        migrations.AddIndex(
            model_name='unitmediafile',
            index=models.Index(fields=['course_id', 'media_type'], name='contentstor_course__b2dc36_idx'),
        ),
        migrations.AddIndex(
            model_name='unitmediafile',
            index=models.Index(fields=['media_type', 'created_at'], name='contentstor_media_t_2573ab_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='unitmediafile',
            unique_together={('unit_id', 'file_name', 'media_type')},
        ),
    ]
