# Generated by Django 4.2.22 on 2025-09-23 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentstore', '0050_unitmediafile_delete_slideconversionjob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitmediafile',
            name='upload_url',
            field=models.URLField(help_text='Public URL for accessing the uploaded file', max_length=500, verbose_name='Upload URL'),
        ),
    ]
