# Generated by Django 4.2.22 on 2025-09-25 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentstore', '0052_add_chalix_quiz_models'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='chalixquiz',
            new_name='contentstor_course__eee874_idx',
            old_name='contentstore_chalixquiz_course_key_is_active_idx',
        ),
        migrations.RenameIndex(
            model_name='chalixquiz',
            new_name='contentstor_parent__7be9a2_idx',
            old_name='contentstore_chalixquiz_parent_locator_is_active_idx',
        ),
        migrations.RenameIndex(
            model_name='chalixquiz',
            new_name='contentstor_created_f16d0d_idx',
            old_name='contentstore_chalixquiz_created_at_idx',
        ),
        migrations.RenameIndex(
            model_name='chalixquizchoice',
            new_name='contentstor_questio_cf49d0_idx',
            old_name='contentstore_chalixquizchoice_question_order_idx',
        ),
        migrations.RenameIndex(
            model_name='chalixquizchoice',
            new_name='contentstor_questio_d24ef7_idx',
            old_name='contentstore_chalixquizchoice_question_is_correct_idx',
        ),
        migrations.RenameIndex(
            model_name='chalixquizquestion',
            new_name='contentstor_quiz_id_55c658_idx',
            old_name='contentstore_chalixquizquestion_quiz_order_idx',
        ),
        migrations.RenameIndex(
            model_name='chalixquizquestion',
            new_name='contentstor_quiz_id_db6740_idx',
            old_name='contentstore_chalixquizquestion_quiz_is_active_idx',
        ),
        migrations.AlterField(
            model_name='chalixquiz',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='chalixquizchoice',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='chalixquizquestion',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
