# Generated by Django 4.2.22 on 2025-10-08 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contentstore', '0054_enforce_chalix_role_constraints'),
        ('contentstore', '0054_update_chalix_role_choices'),
    ]

    operations = [
    ]
