# Generated by Django 4.2.22 on 2025-10-11 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contentstore', '0047_add_final_evaluation_models'),
        ('contentstore', '0055_merge_20251008_2145'),
    ]

    operations = [
    ]
