# Generated by Django 4.2.22 on 2025-10-11 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contentstore', '0048_add_evaluation_fields_to_localprogram'),
        ('contentstore', '0056_merge_20251011_0102'),
    ]

    operations = [
    ]
