# Generated by Django 4.2.22 on 2025-10-12 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contentstore', '0048_update_final_evaluation_unique_constraint'),
        ('contentstore', '0057_merge_20251011_0109'),
    ]

    operations = [
    ]
