# Generated by Django 4.2.22 on 2025-10-17 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contentstore', '0015_add_external_url_support'),
        ('contentstore', '0058_merge_20251012_0242'),
    ]

    operations = [
    ]
