"""Add public_url and url fields to UnitMediaFile

Generated by automated edit
"""
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentstore', '0061_remove_finalevaluation_unique_course_evaluation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitmediafile',
            name='public_url',
            field=models.URLField(blank=True, help_text='Publicly accessible URL for this media (for external videos this maps to external_url)', max_length=1000, null=True, verbose_name='Public URL'),
        ),
        migrations.AddField(
            model_name='unitmediafile',
            name='url',
            field=models.URLField(blank=True, help_text='Alternate URL field retained for compatibility with consumers that expect `url`', max_length=1000, null=True, verbose_name='URL'),
        ),
    ]
