# Generated by Django 4.2.22 on 2025-10-19 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentstore', '0062_add_public_url_and_url_to_unitmediafile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
