# Generated by Django 4.2.22 on 2025-10-19 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contentstore', '0063_organization'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name': 'Organization', 'verbose_name_plural': 'Organizations'},
        ),
    ]
