# Generated by Django 4.2.22 on 2025-11-16 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contentstore', '0002_chalixorganization_admin_delete_organization'),
        ('contentstore', '0069_add_professional_field_model'),
    ]

    operations = [
    ]
