# Generated by Django 4.2.22 on 2026-05-05 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentstore', '0074_add_emotion_adjustment_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chalixstudentemotion',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='chalixtopicemotionaggregate',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
