# Generated by Django 4.2.22 on 2026-06-06 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import opaque_keys.edx.django.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contentstore', '0075_alter_chalixstudentemotion_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChalixSurveyForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_key', opaque_keys.edx.django.models.CourseKeyField(db_index=True, max_length=255, verbose_name='Course Key')),
                ('title', models.CharField(blank=True, help_text='Optional title shown to respondents', max_length=500, verbose_name='Survey Title')),
                ('public_token', models.CharField(blank=True, db_index=True, help_text='URL-safe token used for the shareable survey link', max_length=64, unique=True, verbose_name='Public Token')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_surveys', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Chalix Survey Form',
                'verbose_name_plural': 'Chalix Survey Forms',
            },
        ),
        migrations.CreateModel(
            name='ChalixSurveyChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Training program name shown in the survey', max_length=500, verbose_name='Tên chương trình')),
                ('detail_html', models.TextField(blank=True, help_text='HTML content from the WYSIWYG editor; sanitised via bleach before storage', verbose_name='Chi tiết mô tả chương trình')),
                ('order_index', models.PositiveIntegerField(default=0, verbose_name='Order Index')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='contentstore.chalixsurveyform', verbose_name='Survey')),
            ],
            options={
                'verbose_name': 'Survey Choice',
                'verbose_name_plural': 'Survey Choices',
                'ordering': ['survey', 'order_index'],
            },
        ),
        migrations.AddIndex(
            model_name='chalixsurveyform',
            index=models.Index(fields=['course_key', 'is_active'], name='contentstor_course__6c2ff5_idx'),
        ),
        migrations.AddIndex(
            model_name='chalixsurveychoice',
            index=models.Index(fields=['survey', 'order_index'], name='cstore_survey_choice_order_idx'),
        ),
        migrations.AddIndex(
            model_name='chalixsurveychoice',
            index=models.Index(fields=['survey', 'is_active'], name='cstore_survey_choice_actv_idx'),
        ),
    ]
