# Generated by Django 4.2.22 on 2026-06-06 13:59

from django.db import migrations
import opaque_keys.edx.django.models


class Migration(migrations.Migration):

    dependencies = [
        ('contentstore', '0076_chalixsurveyform_chalixsurveychoice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chalixsurveyform',
            name='course_key',
            field=opaque_keys.edx.django.models.CourseKeyField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Course Key'),
        ),
    ]
