# Generated by Django 4.2.22 on 2026-06-06 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentstore', '0077_make_survey_form_course_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='chalixsurveychoice',
            name='vote_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of votes recorded for this choice', verbose_name='Vote Count'),
        ),
    ]
