# Generated by Django 4.2.22 on 2026-06-07 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentstore', '0078_add_survey_choice_vote_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='chalixsurveychoice',
            name='group_name',
            field=models.CharField(blank=True, default='', help_text="Section header label, e.g. 'NHÓM 1: TÊN CHỦ ĐỀ 1'. Leave blank for ungrouped choices.", max_length=300, verbose_name='Group Name'),
        ),
        migrations.AddField(
            model_name='chalixsurveychoice',
            name='group_order',
            field=models.PositiveIntegerField(default=0, help_text='Controls the display order of groups; choices within the same group_name sort by order_index.', verbose_name='Group Order'),
        ),
        migrations.AlterModelOptions(
            name='chalixsurveychoice',
            options={'ordering': ['survey', 'group_order', 'order_index'], 'verbose_name': 'Survey Choice', 'verbose_name_plural': 'Survey Choices'},
        ),
    ]
