# Generated by Django 4.2.22 on 2026-06-07 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentstore', '0079_add_survey_choice_group_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='chalixsurveyform',
            name='ends_at',
            field=models.DateTimeField(blank=True, help_text='The date and time when the survey expires', null=True, verbose_name='Ends At'),
        ),
        migrations.AddField(
            model_name='chalixsurveyform',
            name='starts_at',
            field=models.DateTimeField(blank=True, help_text='The date and time when the survey becomes active', null=True, verbose_name='Starts At'),
        ),
    ]
