# Generated by Django 3.2 on 2024-01-01 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import opaque_keys.edx.django.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCoursePersonalization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('course_id', opaque_keys.edx.django.models.CourseKeyField(max_length=255, verbose_name='Course ID')),
                ('completed_lessons', models.IntegerField(default=0, verbose_name='Completed Lessons')),
                ('total_lessons', models.IntegerField(default=0, verbose_name='Total Lessons')),
                ('completion_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Completion Percentage')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('paused', 'Paused')], default='not_started', max_length=20, verbose_name='Status')),
                ('time_spent_minutes', models.IntegerField(default=0, verbose_name='Time Spent (minutes)')),
                ('time_spent_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Time Spent (hours)')),
                ('last_accessed', models.DateTimeField(blank=True, null=True, verbose_name='Last Accessed')),
                ('has_certificate', models.BooleanField(default=False, verbose_name='Has Certificate')),
                ('certificate_earned_date', models.DateTimeField(blank=True, null=True, verbose_name='Certificate Earned Date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_personalizations', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Course Personalization',
                'verbose_name_plural': 'User Course Personalizations',
                'db_table': 'personalization_user_course',
                'ordering': ['-modified'],
                'indexes': [
                    models.Index(fields=['user', 'course_id'], name='personaliza_user_id_course_idx'),
                    models.Index(fields=['status'], name='personaliza_status_idx'),
                    models.Index(fields=['last_accessed'], name='personaliza_last_accessed_idx'),
                ],
                'unique_together': {('user', 'course_id')},
            },
        ),
        migrations.CreateModel(
            name='PersonalizationYearlyStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('year', models.IntegerField(verbose_name='Year')),
                ('total_courses', models.IntegerField(default=0, verbose_name='Total Courses')),
                ('active_courses', models.IntegerField(default=0, verbose_name='Active Courses')),
                ('completed_courses', models.IntegerField(default=0, verbose_name='Completed Courses')),
                ('paused_courses', models.IntegerField(default=0, verbose_name='Paused Courses')),
                ('certificates_earned', models.IntegerField(default=0, verbose_name='Certificates Earned')),
                ('total_lessons_completed', models.IntegerField(default=0, verbose_name='Total Lessons Completed')),
                ('total_time_minutes', models.IntegerField(default=0, verbose_name='Total Time (minutes)')),
                ('total_time_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total Time (hours)')),
                ('average_completion_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Average Completion Rate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yearly_stats', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Yearly Statistics',
                'verbose_name_plural': 'Yearly Statistics',
                'db_table': 'personalization_yearly_stats',
                'ordering': ['-year'],
                'indexes': [
                    models.Index(fields=['user', 'year'], name='personaliza_user_id_year_idx'),
                ],
                'unique_together': {('user', 'year')},
            },
        ),
        migrations.CreateModel(
            name='LessonTimeTracking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('lesson_id', models.CharField(max_length=255, verbose_name='Lesson ID')),
                ('time_spent_minutes', models.IntegerField(default=0, verbose_name='Time Spent (minutes)')),
                ('access_count', models.IntegerField(default=0, verbose_name='Access Count')),
                ('last_accessed', models.DateTimeField(auto_now=True, verbose_name='Last Accessed')),
                ('completed', models.BooleanField(default=False, verbose_name='Completed')),
                ('course_personalization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_tracking', to='personalization.usercoursepersonalization', verbose_name='Course Personalization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_time_tracking', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Lesson Time Tracking',
                'verbose_name_plural': 'Lesson Time Tracking',
                'db_table': 'personalization_lesson_tracking',
                'ordering': ['-last_accessed'],
                'indexes': [
                    models.Index(fields=['user', 'lesson_id'], name='personaliza_user_lesson_idx'),
                    models.Index(fields=['last_accessed'], name='personaliza_lesson_last_accessed_idx'),
                ],
                'unique_together': {('user', 'course_personalization', 'lesson_id')},
            },
        ),
    ]
