# Generated by Django 4.2.22 on 2025-11-01 03:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import opaque_keys.edx.django.models


def _drop_index_if_exists(index_name, table_name):
    def _inner(apps, schema_editor):
        connection = schema_editor.connection
        cursor = connection.cursor()
        try:
            constraints = connection.introspection.get_constraints(cursor, table_name)
        except Exception:
            return
        if index_name in constraints:
            try:
                sql = "DROP INDEX `{}` ON `{}`".format(index_name, table_name)
                schema_editor.execute(sql)
            except Exception:
                # best-effort
                pass

    return _inner


def _drop_composed_index_if_exists(column_names, table_name):
    """Return a RunPython callable that drops any index whose columns match
    the given set of column names on the specified table. This is defensive
    for MySQL instances where composed indexes may have been created with
    different names or already removed.
    """

    def _inner(apps, schema_editor):
        connection = schema_editor.connection
        cursor = connection.cursor()
        try:
            constraints = connection.introspection.get_constraints(cursor, table_name)
        except Exception:
            return
        target = set(column_names)
        for name, info in constraints.items():
            cols = info.get('columns') or []
            if set(cols) == target:
                try:
                    sql = "DROP INDEX `{}` ON `{}`".format(name, table_name)
                    schema_editor.execute(sql)
                except Exception:
                    # best-effort
                    pass

    return _inner


def _drop_column_if_exists(column_name, table_name):
    """Return a RunPython callable that drops a column if it exists on the
    specified table."""

    def _inner(apps, schema_editor):
        connection = schema_editor.connection
        cursor = connection.cursor()
        try:
            desc = connection.introspection.get_table_description(cursor, table_name)
            cols = [c[0] for c in desc]
        except Exception:
            return
        if column_name in cols:
            try:
                schema_editor.execute("ALTER TABLE `{}` DROP COLUMN `{}`".format(table_name, column_name))
            except Exception:
                # best-effort
                pass

    return _inner


def _add_column_if_missing(column_name, table_name, column_definition_sql):
    """Return a RunPython callable that adds a column with the given SQL
    definition only if it does not already exist on the table.
    column_definition_sql should be the SQL fragment for the column, e.g.
    "`completed_at` DATETIME NULL".
    """

    def _inner(apps, schema_editor):
        connection = schema_editor.connection
        cursor = connection.cursor()
        try:
            desc = connection.introspection.get_table_description(cursor, table_name)
            cols = [c[0] for c in desc]
        except Exception:
            return
        if column_name not in cols:
            try:
                sql = "ALTER TABLE `{}` ADD COLUMN {}".format(table_name, column_definition_sql)
                schema_editor.execute(sql)
            except Exception:
                # best-effort
                pass

    return _inner


def _add_index_if_missing(index_name, table_name, index_definition_sql):
    """Return a RunPython callable that adds an index only if it doesn't exist.
    index_definition_sql should be the SQL fragment for the index, e.g.
    "ADD INDEX `name` (`col1`, `col2`)".
    """

    def _inner(apps, schema_editor):
        connection = schema_editor.connection
        cursor = connection.cursor()
        try:
            constraints = connection.introspection.get_constraints(cursor, table_name)
        except Exception:
            return
        # If an index with this name or exact columns exists, skip
        for name, info in constraints.items():
            if name == index_name:
                return
        try:
            sql = "ALTER TABLE `{}` {}".format(table_name, index_definition_sql)
            schema_editor.execute(sql)
        except Exception:
            # best-effort
            pass

    return _inner


class Migration(migrations.Migration):
    # Some MySQL DDL statements (ALTER TABLE / RENAME INDEX / DROP INDEX)
    # cannot be executed inside a transaction on MySQL variants that do
    # not support DDL rollback. Several RunPython steps here issue raw
    # ALTER TABLE statements; mark this migration as non-atomic so Django
    # will run operations outside a transaction.
    atomic = False

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('personalization', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessontimetracking',
            options={'ordering': ['-modified'], 'verbose_name': 'Lesson Time Tracking', 'verbose_name_plural': 'Lesson Time Tracking'},
        ),
        migrations.AlterModelOptions(
            name='personalizationyearlystats',
            options={'ordering': ['-year'], 'verbose_name': 'Personalization Yearly Stats', 'verbose_name_plural': 'Personalization Yearly Stats'},
        ),
        migrations.AlterModelOptions(
            name='usercoursepersonalization',
            options={'ordering': ['-last_accessed'], 'verbose_name': 'User Course Personalization', 'verbose_name_plural': 'User Course Personalizations'},
        ),
        migrations.RunPython(_drop_index_if_exists('personaliza_user_lesson_idx', 'personalization_lesson_tracking'), reverse_code=migrations.RunPython.noop),
        migrations.RunPython(_drop_index_if_exists('personaliza_lesson_last_accessed_idx', 'personalization_lesson_tracking'), reverse_code=migrations.RunPython.noop),
        migrations.RunPython(_drop_index_if_exists('personaliza_user_id_course_idx', 'personalization_user_course'), reverse_code=migrations.RunPython.noop),
        migrations.RunPython(_drop_index_if_exists('personaliza_status_idx', 'personalization_user_course'), reverse_code=migrations.RunPython.noop),
        migrations.RunPython(_drop_index_if_exists('personaliza_last_accessed_idx', 'personalization_user_course'), reverse_code=migrations.RunPython.noop),
        # Rename the yearly-stats user index, but MySQL may already have removed
        # the old index. Use a safe RunPython wrapper that renames only when the
        # old index exists. This avoids OperationalError 1176 when the old name
        # isn't present in the database.
        migrations.RunPython(
            lambda apps, schema_editor: (lambda:
                (lambda conn, cur, tbl, old, new: (
                    None if not (lambda constraints: old in constraints)(conn.introspection.get_constraints(cur, tbl)) else (
                        schema_editor.execute("ALTER TABLE `{}` RENAME INDEX `{}` TO `{}`".format(tbl, old, new))
                    )
                ))(schema_editor.connection, schema_editor.connection.cursor(), 'personalization_yearly_stats', 'personaliza_user_id_year_idx', 'personaliza_user_id_249a40_idx')
            )(),
            reverse_code=migrations.RunPython.noop,
        ),
        # Defensive removal of any pre-existing composed unique/index on the
        # lesson tracking table. Different DBs/environments may have created
        # the composed index under different names or column sets
        # (course_personalization_id vs course_id). Drop any matching index
        # if present; otherwise no-op.
        migrations.RunPython(_drop_composed_index_if_exists(['user_id', 'course_personalization_id', 'lesson_id'], 'personalization_lesson_tracking'), reverse_code=migrations.RunPython.noop),
        migrations.RunPython(_drop_composed_index_if_exists(['user_id', 'course_id', 'lesson_id'], 'personalization_lesson_tracking'), reverse_code=migrations.RunPython.noop),
        migrations.RunPython(_drop_column_if_exists('active_courses', 'personalization_yearly_stats'), reverse_code=migrations.RunPython.noop),
        migrations.RunPython(_drop_column_if_exists('average_completion_rate', 'personalization_yearly_stats'), reverse_code=migrations.RunPython.noop),
        migrations.RunPython(_drop_column_if_exists('certificates_earned', 'personalization_yearly_stats'), reverse_code=migrations.RunPython.noop),
        migrations.RunPython(_drop_column_if_exists('completed_courses', 'personalization_yearly_stats'), reverse_code=migrations.RunPython.noop),
        migrations.RunPython(_drop_column_if_exists('paused_courses', 'personalization_yearly_stats'), reverse_code=migrations.RunPython.noop),
        migrations.RunPython(_drop_column_if_exists('total_courses', 'personalization_yearly_stats'), reverse_code=migrations.RunPython.noop),
        migrations.RunPython(_drop_column_if_exists('total_time_hours', 'personalization_yearly_stats'), reverse_code=migrations.RunPython.noop),
        migrations.RunPython(_drop_column_if_exists('total_time_minutes', 'personalization_yearly_stats'), reverse_code=migrations.RunPython.noop),
        migrations.RunPython(_drop_column_if_exists('certificate_earned_date', 'personalization_user_course'), reverse_code=migrations.RunPython.noop),
        migrations.RunPython(_drop_column_if_exists('has_certificate', 'personalization_user_course'), reverse_code=migrations.RunPython.noop),
        migrations.RunPython(_drop_column_if_exists('time_spent_hours', 'personalization_user_course'), reverse_code=migrations.RunPython.noop),
        migrations.RunPython(_drop_column_if_exists('time_spent_minutes', 'personalization_user_course'), reverse_code=migrations.RunPython.noop),
        migrations.RunPython(_add_column_if_missing('completed_at', 'personalization_lesson_tracking', '`completed_at` DATETIME NULL'), reverse_code=migrations.RunPython.noop),
        # Add course_id as CourseKeyField (nullable) only if it doesn't exist.
        # Use RunPython to avoid Django's strict AddField validation which fails on duplicate columns.
        migrations.RunPython(
            lambda apps, schema_editor: _add_column_if_missing('course_id', 'personalization_lesson_tracking', '`course_id` VARCHAR(255) NULL, ADD INDEX `personalization_lesson_tracking_course_id_idx` (`course_id`)')(apps, schema_editor),
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RunPython(_add_column_if_missing('is_completed', 'personalization_lesson_tracking', '`is_completed` TINYINT(1) NOT NULL DEFAULT 0'), reverse_code=migrations.RunPython.noop),
        migrations.RunPython(_add_column_if_missing('lesson_name', 'personalization_lesson_tracking', "`lesson_name` VARCHAR(255) NULL"), reverse_code=migrations.RunPython.noop),
        migrations.RunPython(_add_column_if_missing('average_time_per_course', 'personalization_yearly_stats', '`average_time_per_course` DOUBLE NOT NULL DEFAULT 0'), reverse_code=migrations.RunPython.noop),
        migrations.RunPython(_add_column_if_missing('overall_completion_rate', 'personalization_yearly_stats', '`overall_completion_rate` DOUBLE NOT NULL DEFAULT 0'), reverse_code=migrations.RunPython.noop),
        migrations.RunPython(_add_column_if_missing('total_certificates_earned', 'personalization_yearly_stats', '`total_certificates_earned` INT NOT NULL DEFAULT 0'), reverse_code=migrations.RunPython.noop),
        migrations.RunPython(_add_column_if_missing('total_courses_assigned', 'personalization_yearly_stats', '`total_courses_assigned` INT NOT NULL DEFAULT 0'), reverse_code=migrations.RunPython.noop),
        migrations.RunPython(_add_column_if_missing('total_courses_completed', 'personalization_yearly_stats', '`total_courses_completed` INT NOT NULL DEFAULT 0'), reverse_code=migrations.RunPython.noop),
        migrations.RunPython(_add_column_if_missing('total_study_time_hours', 'personalization_yearly_stats', '`total_study_time_hours` DOUBLE NOT NULL DEFAULT 0'), reverse_code=migrations.RunPython.noop),
        migrations.RunPython(_add_column_if_missing('average_completion_time_per_lesson', 'personalization_user_course', '`average_completion_time_per_lesson` DOUBLE NOT NULL DEFAULT 0'), reverse_code=migrations.RunPython.noop),
        migrations.RunPython(_add_column_if_missing('completed_certificates', 'personalization_user_course', '`completed_certificates` INT NOT NULL DEFAULT 0'), reverse_code=migrations.RunPython.noop),
        migrations.RunPython(_add_column_if_missing('total_certificates', 'personalization_user_course', '`total_certificates` INT NOT NULL DEFAULT 0'), reverse_code=migrations.RunPython.noop),
        migrations.RunPython(_add_column_if_missing('total_study_time', 'personalization_user_course', '`total_study_time` DOUBLE NOT NULL DEFAULT 0'), reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='lessontimetracking',
            name='lesson_id',
            field=models.CharField(db_index=True, help_text='Unique identifier for the lesson/unit', max_length=255),
        ),
        migrations.AlterField(
            model_name='lessontimetracking',
            name='time_spent_minutes',
            field=models.FloatField(default=0.0, help_text='Time spent on this lesson in minutes'),
        ),
        migrations.AlterField(
            model_name='lessontimetracking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_time_tracking', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='personalizationyearlystats',
            name='total_lessons_completed',
            field=models.IntegerField(default=0, help_text='Total lessons completed in the year'),
        ),
        migrations.AlterField(
            model_name='personalizationyearlystats',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yearly_stats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='personalizationyearlystats',
            name='year',
            field=models.IntegerField(db_index=True, help_text='Year for these statistics'),
        ),
        migrations.AlterField(
            model_name='usercoursepersonalization',
            name='completed_lessons',
            field=models.IntegerField(default=0, help_text='Number of completed lessons'),
        ),
        migrations.AlterField(
            model_name='usercoursepersonalization',
            name='completion_percentage',
            field=models.FloatField(default=0.0, help_text='Overall course completion percentage (0-100)'),
        ),
        migrations.AlterField(
            model_name='usercoursepersonalization',
            name='course_id',
            field=opaque_keys.edx.django.models.CourseKeyField(db_index=True, help_text='Course ID for this personalization data', max_length=255),
        ),
        migrations.AlterField(
            model_name='usercoursepersonalization',
            name='last_accessed',
            field=models.DateTimeField(blank=True, help_text='Last time the user accessed this course', null=True),
        ),
        migrations.AlterField(
            model_name='usercoursepersonalization',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('paused', 'Paused')], db_index=True, default='not_started', max_length=20),
        ),
        migrations.AlterField(
            model_name='usercoursepersonalization',
            name='total_lessons',
            field=models.IntegerField(default=0, help_text='Total number of lessons in the course'),
        ),
        migrations.AlterField(
            model_name='usercoursepersonalization',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_personalizations', to=settings.AUTH_USER_MODEL),
        ),
        # Add unique constraint on (user_id, course_id, lesson_id) via safe SQL
        # that works even if the old constraint on (user_id, course_personalization_id, lesson_id)
        # doesn't exist in the DB. We use raw SQL to avoid Django's strict validation
        # which raises ValueError when it cannot find the old constraint to delete.
        migrations.RunPython(
            lambda apps, schema_editor: (
                schema_editor.execute(
                    "ALTER TABLE `personalization_lesson_tracking` ADD CONSTRAINT "
                    "`personalization_lesson_tracking_user_course_lesson_uniq` "
                    "UNIQUE KEY (`user_id`, `course_id`, `lesson_id`)"
                ) if not any(
                    constraint.get('columns') == ['user_id', 'course_id', 'lesson_id']
                    for constraint in schema_editor.connection.introspection.get_constraints(
                        schema_editor.connection.cursor(),
                        'personalization_lesson_tracking'
                    ).values()
                ) else None
            ),
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RunPython(_add_index_if_missing('personaliza_user_id_8184f4_idx', 'personalization_lesson_tracking', "ADD INDEX `personaliza_user_id_8184f4_idx` (`user_id`, `course_id`, `is_completed`)"), reverse_code=migrations.RunPython.noop),
        migrations.RunPython(_add_index_if_missing('personaliza_user_id_d26a1a_idx', 'personalization_user_course', "ADD INDEX `personaliza_user_id_d26a1a_idx` (`user_id`, `status`)"), reverse_code=migrations.RunPython.noop),
        migrations.RunPython(_add_index_if_missing('personaliza_user_id_8b5491_idx', 'personalization_user_course', "ADD INDEX `personaliza_user_id_8b5491_idx` (`user_id`, `completion_percentage`)"), reverse_code=migrations.RunPython.noop),
        migrations.AlterModelTable(
            name='lessontimetracking',
            table=None,
        ),
        migrations.AlterModelTable(
            name='personalizationyearlystats',
            table=None,
        ),
        migrations.AlterModelTable(
            name='usercoursepersonalization',
            table=None,
        ),
        migrations.RunPython(_drop_column_if_exists('access_count', 'personalization_lesson_tracking'), reverse_code=migrations.RunPython.noop),
        migrations.RunPython(_drop_column_if_exists('completed', 'personalization_lesson_tracking'), reverse_code=migrations.RunPython.noop),
        migrations.RunPython(_drop_column_if_exists('course_personalization', 'personalization_lesson_tracking'), reverse_code=migrations.RunPython.noop),
        migrations.RunPython(_drop_column_if_exists('last_accessed', 'personalization_lesson_tracking'), reverse_code=migrations.RunPython.noop),
    ]
