# Generated by Django 4.2.22 on 2025-09-27 09:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Tên loại')),
                ('display_name', models.CharField(max_length=100, verbose_name='Tên hiển thị')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('is_active', models.BooleanField(default=True, verbose_name='Kích hoạt')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Loại thông báo',
                'verbose_name_plural': 'Loại thông báo',
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='UserRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('course_access', 'Yêu cầu truy cập khóa học'), ('certificate', 'Yêu cầu chứng chỉ'), ('grade_review', 'Xem xét điểm số'), ('technical_support', 'Hỗ trợ kỹ thuật'), ('account_issue', 'Vấn đề tài khoản'), ('other', 'Khác')], max_length=20, verbose_name='Loại yêu cầu')),
                ('title', models.CharField(max_length=255, verbose_name='Tiêu đề')),
                ('description', models.TextField(verbose_name='Mô tả chi tiết')),
                ('status', models.CharField(choices=[('open', 'Mở'), ('in_progress', 'Đang xử lý'), ('resolved', 'Đã giải quyết'), ('closed', 'Đã đóng')], default='open', max_length=20, verbose_name='Trạng thái')),
                ('priority', models.CharField(choices=[('low', 'Thấp'), ('medium', 'Trung bình'), ('high', 'Cao'), ('urgent', 'Khẩn cấp')], default='medium', max_length=10, verbose_name='Độ ưu tiên')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True, verbose_name='Ghi chú giải quyết')),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chalix_assigned_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Yêu cầu của người dùng',
                'verbose_name_plural': 'Yêu cầu của người dùng',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserPersonalization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learning_style', models.CharField(blank=True, choices=[('visual', 'Thị giác'), ('auditory', 'Thính giác'), ('kinesthetic', 'Vận động'), ('reading', 'Đọc/Viết')], max_length=20, verbose_name='Phong cách học tập')),
                ('preferred_language', models.CharField(choices=[('vi', 'Tiếng Việt'), ('en', 'English')], default='vi', max_length=10, verbose_name='Ngôn ngữ ưa thích')),
                ('notification_preferences', models.JSONField(default=dict, verbose_name='Tùy chọn thông báo')),
                ('accessibility_preferences', models.JSONField(default=dict, verbose_name='Tùy chọn trợ năng')),
                ('theme_preference', models.CharField(choices=[('light', 'Sáng'), ('dark', 'Tối'), ('auto', 'Tự động')], default='light', max_length=20, verbose_name='Chủ đề giao diện')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personalization', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cá nhân hóa',
                'verbose_name_plural': 'Cá nhân hóa',
            },
        ),
        migrations.CreateModel(
            name='UserLearningPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tiêu đề kế hoạch')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('target_hours', models.PositiveIntegerField(verbose_name='Số giờ mục tiêu')),
                ('completed_hours', models.PositiveIntegerField(default=0, verbose_name='Số giờ đã hoàn thành')),
                ('start_date', models.DateField(verbose_name='Ngày bắt đầu')),
                ('end_date', models.DateField(verbose_name='Ngày kết thúc')),
                ('status', models.CharField(choices=[('draft', 'Bản nháp'), ('active', 'Đang thực hiện'), ('completed', 'Hoàn thành'), ('cancelled', 'Đã hủy')], default='draft', max_length=20, verbose_name='Trạng thái')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kế hoạch học tập',
                'verbose_name_plural': 'Kế hoạch học tập',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeachingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_title', models.CharField(max_length=255, verbose_name='Tiêu đề khóa học')),
                ('course_description', models.TextField(verbose_name='Mô tả khóa học')),
                ('teaching_experience', models.TextField(verbose_name='Kinh nghiệm giảng dạy')),
                ('qualifications', models.TextField(verbose_name='Trình độ chuyên môn')),
                ('proposed_duration', models.PositiveIntegerField(verbose_name='Thời lượng dự kiến (giờ)')),
                ('status', models.CharField(choices=[('pending', 'Chờ phê duyệt'), ('approved', 'Đã phê duyệt'), ('rejected', 'Từ chối'), ('in_review', 'Đang xem xét')], default='pending', max_length=20, verbose_name='Trạng thái')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True, verbose_name='Ghi chú phê duyệt')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chalix_reviewed_teaching_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Đăng ký giảng dạy',
                'verbose_name_plural': 'Đăng ký giảng dạy',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_method', models.CharField(choices=[('web', 'Web'), ('email', 'Email'), ('push', 'Push notification')], max_length=10, verbose_name='Phương thức')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Kích hoạt')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chalix_user_menu.notificationtype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chalix_notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tùy chọn thông báo',
                'verbose_name_plural': 'Tùy chọn thông báo',
                'unique_together': {('user', 'notification_type', 'delivery_method')},
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tiêu đề')),
                ('message', models.TextField(verbose_name='Nội dung')),
                ('priority', models.CharField(choices=[('low', 'Thấp'), ('medium', 'Trung bình'), ('high', 'Cao'), ('urgent', 'Khẩn cấp')], default='medium', max_length=10, verbose_name='Độ ưu tiên')),
                ('is_read', models.BooleanField(default=False, verbose_name='Đã đọc')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Đã lưu trữ')),
                ('action_url', models.URLField(blank=True, verbose_name='Liên kết hành động')),
                ('action_text', models.CharField(blank=True, max_length=100, verbose_name='Văn bản hành động')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Hết hạn vào')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian đọc')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Dữ liệu bổ sung')),
                ('notification_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chalix_user_menu.notificationtype', verbose_name='Loại thông báo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chalix_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Thông báo',
                'verbose_name_plural': 'Thông báo',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='chalix_user_user_id_b81700_idx'), models.Index(fields=['user', 'created_at'], name='chalix_user_user_id_baddb8_idx'), models.Index(fields=['notification_type', 'created_at'], name='chalix_user_notific_123bac_idx')],
            },
        ),
    ]
