# Generated by Django 4.2.22 on 2026-06-07 10:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chalix_user_menu', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChalixDemandSurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_id', models.IntegerField(db_index=True, help_text='PK of the survey model in the contentstore app.', verbose_name='Survey ID')),
                ('full_name', models.CharField(max_length=500, verbose_name='Họ và tên')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone_number', models.CharField(blank=True, max_length=50, verbose_name='Điện thoại')),
                ('other_text', models.CharField(blank=True, max_length=500, verbose_name='Khác')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Submitted At')),
                ('respondent_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demand_survey_responses', to=settings.AUTH_USER_MODEL, verbose_name='Respondent')),
            ],
            options={
                'verbose_name': 'Demand Survey Response',
                'verbose_name_plural': 'Demand Survey Responses',
                'indexes': [models.Index(fields=['survey_id', 'submitted_at'], name='chalix_survey_resp_sid_sub_idx')],
                'unique_together': {('survey_id', 'respondent_user')},
            },
        ),
        migrations.CreateModel(
            name='ChalixDemandSurveyResponseChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_id', models.IntegerField(db_index=True, verbose_name='Choice ID')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_choices', to='chalix_user_menu.chalixdemandsurveyresponse')),
            ],
            options={
                'unique_together': {('response', 'choice_id')},
            },
        ),
    ]
