# Generated by Django 4.2.22 on 2026-06-07 12:09

from django.db import migrations, models
import opaque_keys.edx.django.models


class Migration(migrations.Migration):

    dependencies = [
        ('chalix_user_menu', '0002_add_demand_survey_response'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChalixSurveyChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('detail_html', models.TextField(blank=True)),
                ('order_index', models.PositiveIntegerField(default=0)),
                ('group_name', models.CharField(blank=True, default='', max_length=300)),
                ('group_order', models.PositiveIntegerField(default=0)),
                ('vote_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'contentstore_chalixsurveychoice',
                'ordering': ['group_order', 'order_index'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ChalixSurveyForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_key', opaque_keys.edx.django.models.CourseKeyField(blank=True, db_index=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('public_token', models.CharField(blank=True, db_index=True, max_length=64, unique=True)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'contentstore_chalixsurveyform',
                'managed': False,
            },
        ),
        migrations.RenameIndex(
            model_name='chalixdemandsurveyresponse',
            new_name='chalix_user_survey__a23f89_idx',
            old_name='chalix_survey_resp_sid_sub_idx',
        ),
    ]
