# Generated by Django 4.2.22 on 2025-09-27 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_home_api', '0002_courseemojireview'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='courseemojireview',
            new_name='course_home_course__c99676_idx',
            old_name='course_unit_idx',
        ),
    ]
