# Generated by Django 4.2.22 on 2025-10-02 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_home_api', '0003_rename_course_unit_idx_course_home_course__c99676_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChalixQuizChoiceLMS',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question_id', models.IntegerField(db_index=True)),
                ('choice_text', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('order_index', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'contentstore_chalixquizchoice',
                'ordering': ['question_id', 'order_index'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ChalixQuizLMS',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('course_key', models.CharField(db_index=True, max_length=255)),
                ('parent_locator', models.CharField(db_index=True, max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'contentstore_chalixquiz',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ChalixQuizQuestionLMS',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quiz_id', models.IntegerField(db_index=True)),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(max_length=20)),
                ('order_index', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'contentstore_chalixquizquestion',
                'ordering': ['quiz_id', 'order_index'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UnitMediaFileLMS',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('unit_id', models.CharField(db_index=True, max_length=255)),
                ('course_id', models.CharField(db_index=True, max_length=255)),
                ('media_type', models.CharField(db_index=True, max_length=10)),
                ('file_name', models.CharField(max_length=255)),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('file_size', models.BigIntegerField(default=0)),
                ('file_type', models.CharField(max_length=100)),
                ('file_path', models.CharField(max_length=500)),
                ('upload_url', models.CharField(max_length=500)),
                ('uploaded_by_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'contentstore_unitmediafile',
                'managed': False,
            },
        ),
    ]
