# Generated by Django 4.2.22 on 2025-11-06 23:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course_home_api', '0005_add_final_eval_project_submission'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicQuizAttempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_id', models.BigIntegerField(db_index=True, help_text='Reference to ChalixQuiz id')),
                ('attempt_number', models.PositiveIntegerField(default=1, help_text='Attempt number (always 1 for topic quizzes)')),
                ('started_at', models.DateTimeField(auto_now_add=True, help_text='When attempt started')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When attempt completed', null=True)),
                ('score', models.DecimalField(blank=True, decimal_places=2, help_text='Score percentage', max_digits=5, null=True)),
                ('total_questions', models.PositiveIntegerField(default=0, help_text='Total questions in quiz')),
                ('correct_answers', models.PositiveIntegerField(default=0, help_text='Number of correct answers')),
                ('is_completed', models.BooleanField(default=False, help_text='Whether attempt is completed')),
                ('passed', models.BooleanField(default=True, help_text='Topic quizzes always pass on completion')),
                ('learner', models.ForeignKey(help_text='The learner taking the quiz', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'course_home_api_topic_quiz_attempt',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TopicQuizAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.BigIntegerField(db_index=True, help_text='Reference to ChalixQuizQuestion id')),
                ('selected_choice_id', models.BigIntegerField(blank=True, help_text='Reference to ChalixQuizChoice id', null=True)),
                ('is_correct', models.BooleanField(default=False, help_text='Whether the answer was correct')),
                ('answered_at', models.DateTimeField(auto_now_add=True, help_text='When the answer was submitted')),
                ('attempt', models.ForeignKey(help_text='The quiz attempt this answer belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='course_home_api.topicquizattempt')),
            ],
            options={
                'db_table': 'course_home_api_topic_quiz_answer',
                'managed': True,
            },
        ),
        migrations.AddIndex(
            model_name='topicquizattempt',
            index=models.Index(fields=['quiz_id', 'learner'], name='course_home_quiz_id_fa8b93_idx'),
        ),
        migrations.AddIndex(
            model_name='topicquizattempt',
            index=models.Index(fields=['is_completed'], name='course_home_is_comp_b8d5be_idx'),
        ),
        migrations.AddIndex(
            model_name='topicquizanswer',
            index=models.Index(fields=['attempt', 'question_id'], name='course_home_attempt_277dce_idx'),
        ),
    ]
