version: '3'
services:
  mysql:
    image: mysql:8.0.28
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=alimento128
    networks:
      - chalix-network
      - mysql-network

  mongo:
    image: mongo:7.0.14
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=alimento128
    networks:
      - chalix-network

  redis:
      image: redis:7.2.4-alpine
      container_name: redis
      ports:
        - 6379:6379
      environment:
        - ALLOW_EMPTY_PASSWORD=yes
      volumes:
        - redis_data:/data
      networks:
        - chalix-network
  elasticsearch:
      image: elasticsearch:7.17.8
      container_name: elasticsearch
      ports:
        - 9200:9200
        - 9300:9300
      environment:
        - node.name=elasticsearch
        - cluster.name=docker-cluster
        - bootstrap.memory_lock=false
        - xpack.ml.enabled=false
        - xpack.security.enabled=false
        - discovery.type=single-node
        - "ES_JAVA_OPTS=-Xms1024M -Xmx1024M"
      ulimits:
        nproc: 65535
        nofile:
          soft: 65536
          hard: 65536
        memlock:
          soft: -1
          hard: -1
      volumes:
        - es_data:/usr/share/elasticsearch/data
      networks:
        - chalix-network

networks:
  chalix-network:
    name: chalix-network
  mysql-network:
    name: mysql-network
    driver: bridge

volumes:
  mongo_data:
    driver: local
  redis_data:
    driver: local
  es_data:
    driver: local
  mysql_data:
    driver: local
