CMS_HOST: studio.nuc.ali
CMS_OAUTH2_SECRET: lYzC4JrsY9XIM4EQoxm7QqRF
CONTACT_EMAIL: alimento128@gmail.com
DOCKER_IMAGE_OPENEDX: overhangio/openedx:18.1.3-indigo
ELASTICSEARCH_HEAP_SIZE: 1g
ELASTICSEARCH_HOST: elasticsearch
ELASTICSEARCH_PORT: 9200
ELASTICSEARCH_SCHEME: http
ENABLE_HTTPS: false
ID: k6hoMKjzcaottLGPv369QXr8
JWT_RSA_PRIVATE_KEY: '-----BEGIN RSA PRIVATE KEY-----

  MIIEpAIBAAKCAQEAvcUgZlfaoEIceins+6z6V16VUXHeYs210+mDFC0tKc4Ir8nG

  dHbdWeHN8krQzEndOOueA+5x1fnNyeUhfFJ7wkYwf8fLLhdZ3RZGMZOKnol2HmRn

  eESIvSj0NDi3gRG5GoWNaoWaqKIut/0sk6fvrPle5T+x4hynXp2ImBze4OD6Nleu

  YlOAOVk2N/NZ5upAfnGPJxNuVJIuFBBOk0mzxJlL/24Z1mV3jGG0SBjk0TsT/6OP

  cTgNvbA5T98ra5VC+xDiMIRyINvRnIHzG+vBLnHNO6UoNph4RZwJUCMjPBFWtIVS

  idqnkatu0+RXffUnr1XnVD2C0sVQrS1mIHF7gQIDAQABAoIBAAd8S8CBuWfeJ7up

  ZPXR/098NYFgj5w/30rgQImGlSwbmpPdjpCYQje6DJrAuP7/8GQfBi0DRjYBrCyJ

  N2KNKeDSTjYyIjl7lhG+n87zkhGaHEDLZtnzgR3ODGD1dkaW9YFecIM5yS2a9SMQ

  j2Y1JwMAlK3QDwMbbH4y0lkmtWNzJuw3DZ1/k3k3zX9joTX0IRoKrkh/LKn8FBme

  XQYkvtzwNrSVF5JgY0s3Fyucxbe7j64aI0oqRFM7c0dHAVgiz4HCc2twC94U0zwg

  7zYF+C+oXwYmhuWwOMbgBhcTKITuua5OSKpae5e47YZsCPS36fAKVAh9Gfw/N0yI

  +PReCuECgYEAxsHam+VJgqKkehVWYzMO8tuX+bla/6X4KazIGcDpu/9fsSjQv2Jg

  Jfz2ICyXtycCJnSSXA/rvpLFwlLmSucCWqTrL9NT5g1FtZUOKSlaf947xeT2LEi2

  UyUlaZugPW7TGlWuJqIYb6kyI2mI6Bxuj2cS1rsg6cwkpf76EUBbSLECgYEA9Gyn

  xSee6Cg5pXnU92/gmIWFozm1ysyuoaP6PqZOMRCQv2mK+xFICMbZrAcC7zPU2Am3

  pyN/uwWOFTmS8+N9RKYEgSukTjiHjuTWbKFPMe0247k2IMI8wllcxMGx0LZOZz8e

  LXBj78VEbRy86mLJ9KSUT2M9Tepr+q7EjqlmE9ECgYEAtivP1rudWOMBpfQQrfOK

  bAXhkb3WLiNNBcWb0h8DHJDAgHxMeF4OikMExBCbLf/O9Lg7va3KAW49XBLniReb

  DMHD3p3vdBgOIJRx2kBQ9ooWdxeYmpY6ppKRa+58PFJrouONL1O62f1WOybrmPMW

  UtHCbpYtYJz/qjW9tjoqcMECgYEAzBAm5XAVuCdVMXUMu2QZM91N3B9jSiQmq+bW

  FxYLc+Uro9L+6GveIw25T2kvJvuz+IXsYUs+6apSnB/MM3g67mRYoGsKKxABBOjC

  qEDoeHtedzL7INBpn6yxyccYqHJ79LD6hd8uYFDmtt3mTx0ZFPmOpNTqqrFLYygk

  DCMbiPECgYAkQ7wkTsrkN8HpFSuhZ2VC/BWyrB92QCvVAwHhoAHGndxWD+uJgYqQ

  Fr/wKrNK8ilZsaeFLMMd6hHHc5IFoThqGPIxlosSFP/yMjf7Ap5kuMcW6S06/ybU

  +Et5KogNradedL7N0ZdV5oW5yST2YlhuAN0xHIeImNa06FW4tMHVHA==

  -----END RSA PRIVATE KEY-----'
LANGUAGE_CODE: en
LMS_HOST: nuc.ali
MINIO_AWS_SECRET_ACCESS_KEY: V4K9LXB3BA6YldhRKllUz1lN
MINIO_DOCKER_IMAGE: quay.io/minio/minio:RELEASE.2024-09-22T00-33-43Z
MINIO_MC_DOCKER_IMAGE: docker.io/minio/mc:RELEASE.2024-09-16T17-43-14Z
MONGODB_HOST: mongo
MONGODB_PASSWORD: alimento128
MONGODB_USERNAME: admin
MOUNTS:
- /home/alimento/dungdl/code/chalix-ed
MYSQL_HOST: mysql
MYSQL_PORT: 3306
MYSQL_ROOT_PASSWORD: alimento128
MYSQL_ROOT_USERNAME: root
OPENEDX_AWS_ACCESS_KEY: alimento
OPENEDX_AWS_SECRET_ACCESS_KEY: alimento128
OPENEDX_CMS_UWSGI_WORKERS: 8
OPENEDX_LMS_UWSGI_WORKERS: 8
OPENEDX_MYSQL_PASSWORD: xgMywnTs
OPENEDX_SECRET_KEY: ITN95HXgEgrYSKpFjssNzgZs
PLATFORM_NAME: Chalix Edu
PLUGINS:
- indigo
- mfe
- minio
- videoupload
PLUGIN_INDEXES:
- https://overhang.io/tutor/main
REDIS_HOST: redis
REDIS_PORT: 6379
RUN_ELASTICSEARCH: false
RUN_FORUM: false
RUN_MONGODB: false
RUN_MYSQL: false
RUN_REDIS: false
RUN_SMTP: false
