# Generated by Django 4.2.22 on 2025-10-02 22:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learning_analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecredithours',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='learnerbehavior',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='learnerrecommendation',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='learninggoal',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='learninghoursapproval',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='learninghoursrequirement',
            name='current_year',
            field=models.IntegerField(default=2025),
        ),
        migrations.AlterField(
            model_name='learninghoursrequirement',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='studentcourseprogress',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.RunSQL(
            sql=(
                "CREATE UNIQUE INDEX `ux_learning_analytics_learnerbehavior_user_course` "
                "ON `learning_analytics_learnerbehavior` (`user_id`, `course_id`);"
            ),
            reverse_sql=(
                "DROP INDEX `ux_learning_analytics_learnerbehavior_user_course` "
                "ON `learning_analytics_learnerbehavior`;"
            ),
        ),
    ]
