# Generated by Django 4.2.22 on 2025-10-02 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_analytics', '0002_alter_coursecredithours_id_alter_learnerbehavior_id_and_more'),
        ('learning_analytics', '0002_create_missing_tables'),
    ]

    operations = [
    ]
