# Generated by Django 4.2.22 on 2025-10-02 22:13

from django.conf import settings
from django.db import migrations


def create_unique_index_if_missing(apps, schema_editor):
    """Create a unique index on (user_id, course_id) if one doesn't exist."""
    connection = schema_editor.connection
    table_name = 'learning_analytics_learnerbehavior'

    # Introspect existing constraints/indexes
    constraints = connection.introspection.get_constraints(connection.cursor(), table_name)

    # Check if a unique constraint/index already exists on user_id + course_id
    exists = False
    for name, info in constraints.items():
        if info.get('unique') and tuple(info.get('columns', [])) == ('user_id', 'course_id'):
            exists = True
            break

    if not exists:
        # Create a uniquely-named index to avoid auto-generated name collisions
        sql = (
            "CREATE UNIQUE INDEX `ux_learning_analytics_learnerbehavior_user_course` "
            "ON `{}` (`user_id`, `course_id`)".format(table_name)
        )
        schema_editor.execute(sql)


def drop_unique_index_if_exists(apps, schema_editor):
    connection = schema_editor.connection
    table_name = 'learning_analytics_learnerbehavior'
    index_name = 'ux_learning_analytics_learnerbehavior_user_course'

    # Introspect existing constraints/indexes
    constraints = connection.introspection.get_constraints(connection.cursor(), table_name)
    if index_name in constraints:
        # Drop the index
        sql = "DROP INDEX `{}` ON `{}`".format(index_name, table_name)
        schema_editor.execute(sql)


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learning_analytics', '0003_merge_20251002_2207'),
    ]

    operations = [
        migrations.RunPython(create_unique_index_if_missing, reverse_code=drop_unique_index_if_exists),
    ]
