# Generated by Django 4.2.22 on 2025-10-02 22:16

from django.conf import settings
from django.db import migrations


def create_unique_index_if_missing_0005(apps, schema_editor):
    connection = schema_editor.connection
    table_name = 'learning_analytics_learnerbehavior'
    cursor = connection.cursor()

    constraints = connection.introspection.get_constraints(cursor, table_name)

    exists = False
    for name, info in constraints.items():
        if info.get('unique') and tuple(info.get('columns', [])) == ('user_id', 'course_id'):
            exists = True
            break

    if not exists:
        sql = (
            "CREATE UNIQUE INDEX `ux_learning_analytics_learnerbehavior_user_course` "
            "ON `{}` (`user_id`, `course_id`)".format(table_name)
        )
        schema_editor.execute(sql)


def drop_unique_index_if_exists_0005(apps, schema_editor):
    connection = schema_editor.connection
    table_name = 'learning_analytics_learnerbehavior'
    index_name = 'ux_learning_analytics_learnerbehavior_user_course'
    cursor = connection.cursor()

    constraints = connection.introspection.get_constraints(cursor, table_name)
    if index_name in constraints:
        sql = "DROP INDEX `{}` ON `{}`".format(index_name, table_name)
        schema_editor.execute(sql)


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learning_analytics', '0004_alter_learnerbehavior_unique_together'),
    ]

    operations = [
        migrations.RunPython(create_unique_index_if_missing_0005, reverse_code=drop_unique_index_if_exists_0005),
    ]
