# Generated by Django 4.2.22 on 2025-10-02 22:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learning_analytics', '0005_alter_learnerbehavior_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='learnerbehavior',
            unique_together={('user', 'course_id')},
        ),
    ]
