# Generated by Django 4.2.22 on 2025-11-02 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_analytics', '0002_facial_expression_log'),
        ('learning_analytics', '0006_alter_learnerbehavior_unique_together'),
    ]

    operations = [
    ]
