# Generated by Django 4.2.22 on 2025-11-02 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_analytics', '0007_merge_20251102_1351'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='facialexpressionlog',
            new_name='learning_an_user_id_bb03fa_idx',
            old_name='learning_an_user_id_course_idx',
        ),
        migrations.RenameIndex(
            model_name='facialexpressionlog',
            new_name='learning_an_course__8e1415_idx',
            old_name='learning_an_course_unit_idx',
        ),
        migrations.RenameIndex(
            model_name='facialexpressionlog',
            new_name='learning_an_start_t_675d1c_idx',
            old_name='learning_an_start_t_idx',
        ),
        migrations.RenameIndex(
            model_name='facialexpressionlog',
            new_name='learning_an_process_76f1f0_idx',
            old_name='learning_an_process_idx',
        ),
    ]
