# Generated by Django 4.2.26 on 2026-05-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_analytics', '0015_learnerbehavior_materials_opened'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentlearningprocesssnapshot',
            name='estimated_week_1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='studentlearningprocesssnapshot',
            name='estimated_week_2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='studentlearningprocesssnapshot',
            name='estimated_week_3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddConstraint(
            model_name='studentlearningprocesssnapshot',
            constraint=models.CheckConstraint(
                check=models.Q(('estimated_week_1__isnull', True), ('estimated_week_1__gte', 0), _connector='OR') & models.Q(('estimated_week_1__isnull', True), ('estimated_week_1__lte', 10), _connector='OR'),
                name='la_snapshot_estimated_week_1_0_10',
            ),
        ),
        migrations.AddConstraint(
            model_name='studentlearningprocesssnapshot',
            constraint=models.CheckConstraint(
                check=models.Q(('estimated_week_2__isnull', True), ('estimated_week_2__gte', 0), _connector='OR') & models.Q(('estimated_week_2__isnull', True), ('estimated_week_2__lte', 10), _connector='OR'),
                name='la_snapshot_estimated_week_2_0_10',
            ),
        ),
        migrations.AddConstraint(
            model_name='studentlearningprocesssnapshot',
            constraint=models.CheckConstraint(
                check=models.Q(('estimated_week_3__isnull', True), ('estimated_week_3__gte', 0), _connector='OR') & models.Q(('estimated_week_3__isnull', True), ('estimated_week_3__lte', 10), _connector='OR'),
                name='la_snapshot_estimated_week_3_0_10',
            ),
        ),
    ]
